# Generated by Django 5.1.2 on 2024-10-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='singleorder',
            name='orderid',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='production.order'),
            preserve_default=False,
        ),
    ]
