# Generated by Django 5.1.2 on 2024-10-20 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_singleorder_order_alter_singleorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='production.order'),
        ),
    ]
