# Generated by Django 5.1.2 on 2024-10-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_order_status_productrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
