# Generated by Django 5.1.2 on 2024-10-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_description_products_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='feature',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
